name: Build and deploy XSSHunter to Azure

on:
  push:
    branches:
      - main  # or master, depending on your repo

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  WEBAPP_NAME: ${{ secrets.WEBAPP_NAME }}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name $ACR_NAME

      - name: Build and push image to ACR
        run: |
          IMAGE="$ACR_NAME.azurecr.io/xsshunter:latest"
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          images: ${{ env.ACR_NAME }}.azurecr.io/xsshunter:latest
